# Loading Data

In [3]:
import pandas as pd

In [4]:
url = 'https://data.elexon.co.uk/bmrs/api/v1/datasets/FUELINST?format=json'

In [5]:
elexon_df = pd.read_json(url)

In [6]:
elexon_df

                                                   data
0     {'dataset': 'FUELINST', 'publishTime': '2026-0...
1     {'dataset': 'FUELINST', 'publishTime': '2026-0...
2     {'dataset': 'FUELINST', 'publishTime': '2026-0...
3     {'dataset': 'FUELINST', 'publishTime': '2026-0...
4     {'dataset': 'FUELINST', 'publishTime': '2026-0...
...                                                 ...
3135  {'dataset': 'FUELINST', 'publishTime': '2026-0...
3136  {'dataset': 'FUELINST', 'publishTime': '2026-0...
3137  {'dataset': 'FUELINST', 'publishTime': '2026-0...
3138  {'dataset': 'FUELINST', 'publishTime': '2026-0...
3139  {'dataset': 'FUELINST', 'publishTime': '2026-0...

[3140 rows x 1 columns]

In [7]:
elexon_df['data']

0       {'dataset': 'FUELINST', 'publishTime': '2026-0...
1       {'dataset': 'FUELINST', 'publishTime': '2026-0...
2       {'dataset': 'FUELINST', 'publishTime': '2026-0...
3       {'dataset': 'FUELINST', 'publishTime': '2026-0...
4       {'dataset': 'FUELINST', 'publishTime': '2026-0...
                              ...
3135    {'dataset': 'FUELINST', 'publishTime': '2026-0...
3136    {'dataset': 'FUELINST', 'publishTime': '2026-0...
3137    {'dataset': 'FUELINST', 'publishTime': '2026-0...
3138    {'dataset': 'FUELINST', 'publishTime': '2026-0...
3139    {'dataset': 'FUELINST', 'publishTime': '2026-0...
Name: data, Length: 3140, dtype: object

In [8]:
# expand the dictionaries inside the "data" column
df = pd.json_normalize(elexon_df["data"])
df

,dataset,publishTime,startTime,settlementDate,settlementPeriod,fuelType,generation
0,FUELINST,2026-03-09T13:05:00Z,2026-03-09T13:00:00Z,2026-03-09,27,BIOMASS,2856
1,FUELINST,2026-03-09T13:05:00Z,2026-03-09T13:00:00Z,2026-03-09,27,CCGT,17775
2,FUELINST,2026-03-09T13:05:00Z,2026-03-09T13:00:00Z,2026-03-09,27,COAL,0
3,FUELINST,2026-03-09T13:05:00Z,2026-03-09T13:00:00Z,2026-03-09,27,INTELEC,998
4,FUELINST,2026-03-09T13:05:00Z,2026-03-09T13:00:00Z,2026-03-09,27,INTEW,-264
...,...,...,...,...,...,...,...
3135,FUELINST,2026-03-09T00:05:00Z,2026-03-09T00:00:00Z,2026-03-09,1,OCGT,3
3136,FUELINST,2026-03-09T00:05:00Z,2026-03-09T00:00:00Z,2026-03-09,1,OIL,0
3137,FUELINST,2026-03-09T00:05:00Z,2026-03-09T00:00:00Z,2026-03-09,1,OTHER,217
3138,FUELINST,2026-03-09T00:05:00Z,2026-03-09T00:00:00Z,2026-03-09,1,PS,-127
3139,FUELINST,2026-03-09T00:05:00Z,2026-03-09T00:00:00Z,2026-03-09,1,WIND,3552

# Data Preprocessing

In [35]:
df.sample(20)

,dataset,publishTime,startTime,settlementDate,settlementPeriod,fuelType,generation
2975,FUELINST,2026-03-09T00:45:00Z,2026-03-09T00:40:00Z,2026-03-09,2,OCGT,3
2857,FUELINST,2026-03-09T01:15:00Z,2026-03-09T01:10:00Z,2026-03-09,3,OTHER,697
1200,FUELINST,2026-03-09T08:05:00Z,2026-03-09T08:00:00Z,2026-03-09,17,BIOMASS,2872
170,FUELINST,2026-03-09T12:25:00Z,2026-03-09T12:20:00Z,2026-03-09,25,INTNEM,1017
732,FUELINST,2026-03-09T10:05:00Z,2026-03-09T10:00:00Z,2026-03-09,21,INTVKL,986
2409,FUELINST,2026-03-09T03:05:00Z,2026-03-09T03:00:00Z,2026-03-09,7,INTNED,1049
2118,FUELINST,2026-03-09T04:20:00Z,2026-03-09T04:15:00Z,2026-03-09,9,PS,-493
533,FUELINST,2026-03-09T10:55:00Z,2026-03-09T10:50:00Z,2026-03-09,22,NPSHYD,718
2732,FUELINST,2026-03-09T01:45:00Z,2026-03-09T01:40:00Z,2026-03-09,4,INTVKL,992
1120,FUELINST,2026-03-09T08:25:00Z,2026-03-09T08:20:00Z,2026-03-09,17,BIOMASS,2869
2494,FUELINST,2026-03-09T02:45:00Z,2026-03-09T02:40:00Z,2026-03-09,6,NUCLEAR,2852
2448,FUELINST,2026-03-09T02:55:00Z,2026-03-09T02:50:00Z,2026-03-09,6,INTIRL,-119
2666,FUELINST,2026-03-09T02:00:00Z,2026-03-09T01:55:00Z,2026-03-09,4,INTGRNL,-513
328,FUELINST,2026-03-09T11:45:00Z,2026-03-09T11:40:00Z,2026-03-09,24,INTIRL,-451
1992,FUELINST,2026-03-09T04:50:00Z,2026-03-09T04:45:00Z,2026-03-09,10,INTVKL,774
1426,FUELINST,2026-03-09T07:10:00Z,2026-03-09T07:05:00Z,2026-03-09,15,INTGRNL,-514
557,FUELINST,2026-03-09T10:50:00Z,2026-03-09T10:45:00Z,2026-03-09,22,OTHER,491
456,FUELINST,2026-03-09T11:15:00Z,2026-03-09T11:10:00Z,2026-03-09,23,OIL,0
2985,FUELINST,2026-03-09T00:40:00Z,2026-03-09T00:35:00Z,2026-03-09,2,INTFR,1503
2167,FUELINST,2026-03-09T04:05:00Z,2026-03-09T04:00:00Z,2026-03-09,9,INTIFA2,991

In [57]:
df[df['settlementPeriod'] == 2]

,dataset,publishTime,startTime,settlementDate,settlementPeriod,fuelType,generation
2900,FUELINST,2026-03-09T01:00:00Z,2026-03-09T13:00:00Z,2026-03-09,2,BIOMASS,2862
2901,FUELINST,2026-03-09T01:00:00Z,2026-03-09T13:00:00Z,2026-03-09,2,CCGT,8568
2902,FUELINST,2026-03-09T01:00:00Z,2026-03-09T13:00:00Z,2026-03-09,2,COAL,0
2903,FUELINST,2026-03-09T01:00:00Z,2026-03-09T13:00:00Z,2026-03-09,2,INTELEC,998
2904,FUELINST,2026-03-09T01:00:00Z,2026-03-09T13:00:00Z,2026-03-09,2,INTEW,0
...,...,...,...,...,...,...,...
3015,FUELINST,2026-03-09T00:35:00Z,2026-03-09T13:00:00Z,2026-03-09,2,OCGT,3
3016,FUELINST,2026-03-09T00:35:00Z,2026-03-09T13:00:00Z,2026-03-09,2,OIL,0
3017,FUELINST,2026-03-09T00:35:00Z,2026-03-09T13:00:00Z,2026-03-09,2,OTHER,432
3018,FUELINST,2026-03-09T00:35:00Z,2026-03-09T13:00:00Z,2026-03-09,2,PS,-125
3019,FUELINST,2026-03-09T00:35:00Z,2026-03-09T13:00:00Z,2026-03-09,2,WIND,3514

In [55]:
df[(df['fuelType'] == 'NUCLEAR') & (df['settlementPeriod'] == 1)]

,dataset,publishTime,startTime,settlementDate,settlementPeriod,fuelType,generation
3034,FUELINST,2026-03-09T00:30:00Z,2026-03-09T13:00:00Z,2026-03-09,1,NUCLEAR,2853
3054,FUELINST,2026-03-09T00:25:00Z,2026-03-09T13:00:00Z,2026-03-09,1,NUCLEAR,2855
3074,FUELINST,2026-03-09T00:20:00Z,2026-03-09T13:00:00Z,2026-03-09,1,NUCLEAR,2850
3094,FUELINST,2026-03-09T00:15:00Z,2026-03-09T13:00:00Z,2026-03-09,1,NUCLEAR,2850
3114,FUELINST,2026-03-09T00:10:00Z,2026-03-09T13:00:00Z,2026-03-09,1,NUCLEAR,2856
3134,FUELINST,2026-03-09T00:05:00Z,2026-03-09T13:00:00Z,2026-03-09,1,NUCLEAR,2890

In [37]:
df['fuelType'].unique()

array(['BIOMASS', 'CCGT', 'COAL', 'INTELEC', 'INTEW', 'INTFR', 'INTGRNL',
       'INTIFA2', 'INTIRL', 'INTNED', 'INTNEM', 'INTNSL', 'INTVKL',
       'NPSHYD', 'NUCLEAR', 'OCGT', 'OIL', 'OTHER', 'PS', 'WIND'],
      dtype=object)

In [50]:
df[df['startTime'] == '2026-03-09T13:00:00Z']

,dataset,publishTime,startTime,settlementDate,settlementPeriod,fuelType,generation
0,FUELINST,2026-03-09T13:05:00Z,2026-03-09T13:00:00Z,2026-03-09,27,BIOMASS,2856
1,FUELINST,2026-03-09T13:05:00Z,2026-03-09T13:00:00Z,2026-03-09,27,CCGT,17775
2,FUELINST,2026-03-09T13:05:00Z,2026-03-09T13:00:00Z,2026-03-09,27,COAL,0
3,FUELINST,2026-03-09T13:05:00Z,2026-03-09T13:00:00Z,2026-03-09,27,INTELEC,998
4,FUELINST,2026-03-09T13:05:00Z,2026-03-09T13:00:00Z,2026-03-09,27,INTEW,-264
...,...,...,...,...,...,...,...
3135,FUELINST,2026-03-09T00:05:00Z,2026-03-09T13:00:00Z,2026-03-09,1,OCGT,3
3136,FUELINST,2026-03-09T00:05:00Z,2026-03-09T13:00:00Z,2026-03-09,1,OIL,0
3137,FUELINST,2026-03-09T00:05:00Z,2026-03-09T13:00:00Z,2026-03-09,1,OTHER,217
3138,FUELINST,2026-03-09T00:05:00Z,2026-03-09T13:00:00Z,2026-03-09,1,PS,-127
3139,FUELINST,2026-03-09T00:05:00Z,2026-03-09T13:00:00Z,2026-03-09,1,WIND,3552

In [10]:
df.shape

(3140, 7)

In [11]:
df.size

21980

In [17]:
df.isnull().sum()

dataset             0
publishTime         0
startTime           0
settlementDate      0
settlementPeriod    0
fuelType            0
generation          0
dtype: int64

In [20]:
df.dtypes

dataset             object
publishTime         object
startTime           object
settlementDate      object
settlementPeriod     int64
fuelType            object
generation           int64
dtype: object