In [91]:
import pandas as pd
import requests

In [92]:
url = 'https://api.open-meteo.com/v1/forecast?latitude=51.5&longitude=-0.1&hourly=wind_speed_10m,temperature_2m,shortwave_radiation'

## using pd.json_read

In [93]:
data = pd.read_json(url)
data

,latitude,longitude,generationtime_ms,utc_offset_seconds,timezone,timezone_abbreviation,elevation,hourly_units,hourly
time,51.49288,-0.102875,749.892592,0,GMT,GMT,12,iso8601,"[2026-03-09T00:00, 2026-03-09T01:00, 2026-03-0..."
wind_speed_10m,51.49288,-0.102875,749.892592,0,GMT,GMT,12,km/h,"[4.7, 5.8, 4.7, 3.2, 4.0, 4.0, 4.3, 3.6, 3.2, ..."
temperature_2m,51.49288,-0.102875,749.892592,0,GMT,GMT,12,°C,"[8.2, 8.2, 7.8, 8.1, 8.1, 7.9, 7.8, 7.9, 7.8, ..."
shortwave_radiation,51.49288,-0.102875,749.892592,0,GMT,GMT,12,W/m²,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.0, 40.0,..."

In [94]:
data['hourly']

time                   [2026-03-09T00:00, 2026-03-09T01:00, 2026-03-0...
wind_speed_10m         [4.7, 5.8, 4.7, 3.2, 4.0, 4.0, 4.3, 3.6, 3.2, ...
temperature_2m         [8.2, 8.2, 7.8, 8.1, 8.1, 7.9, 7.8, 7.9, 7.8, ...
shortwave_radiation    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.0, 40.0,...
Name: hourly, dtype: object

In [95]:
df = pd.DataFrame(data['hourly'])
df

                                                                hourly
time                 [2026-03-09T00:00, 2026-03-09T01:00, 2026-03-0...
wind_speed_10m       [4.7, 5.8, 4.7, 3.2, 4.0, 4.0, 4.3, 3.6, 3.2, ...
temperature_2m       [8.2, 8.2, 7.8, 8.1, 8.1, 7.9, 7.8, 7.9, 7.8, ...
shortwave_radiation  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.0, 40.0,...

In [96]:
df["hourly"].apply(pd.Series).T

                 time wind_speed_10m temperature_2m shortwave_radiation
0    2026-03-09T00:00            4.7            8.2                 0.0
1    2026-03-09T01:00            5.8            8.2                 0.0
2    2026-03-09T02:00            4.7            7.8                 0.0
3    2026-03-09T03:00            3.2            8.1                 0.0
4    2026-03-09T04:00            4.0            8.1                 0.0
..                ...            ...            ...                 ...
163  2026-03-15T19:00           17.6           10.5                 0.0
164  2026-03-15T20:00           16.2           10.4                 0.0
165  2026-03-15T21:00           14.8           10.1                 0.0
166  2026-03-15T22:00           13.3            9.9                 0.0
167  2026-03-15T23:00           11.9            9.7                 0.0

[168 rows x 4 columns]

# Using request.get()

In [97]:
response = requests.get(url).json()
response

{'latitude': 51.49288,
 'longitude': -0.102874756,
 'generationtime_ms': 292.0079231262207,
 'utc_offset_seconds': 0,
 'timezone': 'GMT',
 'timezone_abbreviation': 'GMT',
 'elevation': 12.0,
 'hourly_units': {'time': 'iso8601',
  'wind_speed_10m': 'km/h',
  'temperature_2m': '°C',
  'shortwave_radiation': 'W/m²'},
 'hourly': {'time': ['2026-03-09T00:00',
   '2026-03-09T01:00',
   '2026-03-09T02:00',
   '2026-03-09T03:00',
   '2026-03-09T04:00',
   '2026-03-09T05:00',
   '2026-03-09T06:00',
   '2026-03-09T07:00',
   '2026-03-09T08:00',
   '2026-03-09T09:00',
   '2026-03-09T10:00',
   '2026-03-09T11:00',
   '2026-03-09T12:00',
   '2026-03-09T13:00',
   '2026-03-09T14:00',
   '2026-03-09T15:00',
   '2026-03-09T16:00',
   '2026-03-09T17:00',
   '2026-03-09T18:00',
   '2026-03-09T19:00',
   '2026-03-09T20:00',
   '2026-03-09T21:00',
   '2026-03-09T22:00',
   '2026-03-09T23:00',
   '2026-03-10T00:00',
   '2026-03-10T01:00',
   '2026-03-10T02:00',
   '2026-03-10T03:00',
   '2026-03-10T04:00',
   '2026-03-10T05:00',
   '2026-03-10T06:00',
   '2026-03-10T07:00',
   '2026-03-10T08:00',
   '2026-03-10T09:00',
   '2026-03-10T10:00',
   '2026-03-10T11:00',
   '2026-03-10T12:00',
   '2026-03-10T13:00',
   '2026-03-10T14:00',
   '2026-03-10T15:00',
   '2026-03-10T16:00',
   '2026-03-10T17:00',
   '2026-03-10T18:00',
   '2026-03-10T19:00',
   '2026-03-10T20:00',
   '2026-03-10T21:00',
   '2026-03-10T22:00',
   '2026-03-10T23:00',
   '2026-03-11T00:00',
   '2026-03-11T01:00',
   '2026-03-11T02:00',
   '2026-03-11T03:00',
   '2026-03-11T04:00',
   '2026-03-11T05:00',
   '2026-03-11T06:00',
   '2026-03-11T07:00',
   '2026-03-11T08:00',
   '2026-03-11T09:00',
   '2026-03-11T10:00',
   '2026-03-11T11:00',
   '2026-03-11T12:00',
   '2026-03-11T13:00',
   '2026-03-11T14:00',
   '2026-03-11T15:00',
   '2026-03-11T16:00',
   '2026-03-11T17:00',
   '2026-03-11T18:00',
   '2026-03-11T19:00',
   '2026-03-11T20:00',
   '2026-03-11T21:00',
   '2026-03-11T22:00',
   '2026-03-11T23:00',
   '2026-03-12T00:00',
   '2026-03-12T01:00',
   '2026-03-12T02:00',
   '2026-03-12T03:00',
   '2026-03-12T04:00',
   '2026-03-12T05:00',
   '2026-03-12T06:00',
   '2026-03-12T07:00',
   '2026-03-12T08:00',
   '2026-03-12T09:00',
   '2026-03-12T10:00',
   '2026-03-12T11:00',
   '2026-03-12T12:00',
   '2026-03-12T13:00',
   '2026-03-12T14:00',
   '2026-03-12T15:00',
   '2026-03-12T16:00',
   '2026-03-12T17:00',
   '2026-03-12T18:00',
   '2026-03-12T19:00',
   '2026-03-12T20:00',
   '2026-03-12T21:00',
   '2026-03-12T22:00',
   '2026-03-12T23:00',
   '2026-03-13T00:00',
   '2026-03-13T01:00',
   '2026-03-13T02:00',
   '2026-03-13T03:00',
   '2026-03-13T04:00',
   '2026-03-13T05:00',
   '2026-03-13T06:00',
   '2026-03-13T07:00',
   '2026-03-13T08:00',
   '2026-03-13T09:00',
   '2026-03-13T10:00',
   '2026-03-13T11:00',
   '2026-03-13T12:00',
   '2026-03-13T13:00',
   '2026-03-13T14:00',
   '2026-03-13T15:00',
   '2026-03-13T16:00',
   '2026-03-13T17:00',
   '2026-03-13T18:00',
   '2026-03-13T19:00',
   '2026-03-13T20:00',
   '2026-03-13T21:00',
   '2026-03-13T22:00',
   '2026-03-13T23:00',
   '2026-03-14T00:00',
   '2026-03-14T01:00',
   '2026-03-14T02:00',
   '2026-03-14T03:00',
   '2026-03-14T04:00',
   '2026-03-14T05:00',
   '2026-03-14T06:00',
   '2026-03-14T07:00',
   '2026-03-14T08:00',
   '2026-03-14T09:00',
   '2026-03-14T10:00',
   '2026-03-14T11:00',
   '2026-03-14T12:00',
   '2026-03-14T13:00',
   '2026-03-14T14:00',
   '2026-03-14T15:00',
   '2026-03-14T16:00',
   '2026-03-14T17:00',
   '2026-03-14T18:00',
   '2026-03-14T19:00',
   '2026-03-14T20:00',
   '2026-03-14T21:00',
   '2026-03-14T22:00',
   '2026-03-14T23:00',
   '2026-03-15T00:00',
   '2026-03-15T01:00',
   '2026-03-15T02:00',
   '2026-03-15T03:00',
   '2026-03-15T04:00',
   '2026-03-15T05:00',
   '2026-03-15T06:00',
   '2026-03-15T07:00',
   '2026-03-15T08:00',
   '2026-03-15T09:00',
   '2026-03-15T10:00',
   '2026-03-15T11:00',
   '2026-03-15T12:00',
   '2026-03-15T13:00',
   '2026-03-15T14:00',
   '2026-03-15T15:00',
   '2026-03-15T16:00',
   '2026-03-15T17:00',
   '2026-03-15T18:00',
   '2026-03-15T19:00',
   '2026-03-15T20:00',
   '2026-03-15T21:00',
   '2026-03-15T22:00',
   '2026-03-15T23:00'],
  'wind_speed_10m': [4.7,
   5.8,
   4.7,
   3.2,
   4.0,
   4.0,
   4.3,
   3.6,
   3.2,
   4.7,
   2.5,
   2.9,
   5.4,
   5.0,
   5.0,
   9.0,
   11.2,
   11.2,
   12.2,
   11.2,
   10.4,
   11.2,
   11.2,
   7.9,
   6.8,
   10.8,
   10.1,
   9.4,
   12.2,
   10.4,
   9.4,
   9.0,
   9.4,
   7.9,
   9.4,
   12.2,
   13.3,
   15.5,
   15.5,
   17.3,
   17.6,
   18.4,
   18.4,
   17.6,
   16.6,
   15.5,
   16.6,
   17.6,
   19.4,
   20.5,
   19.4,
   22.7,
   20.2,
   12.6,
   11.9,
   14.8,
   17.6,
   17.3,
   18.2,
   17.8,
   17.8,
   17.6,
   17.6,
   17.6,
   17.6,
   17.3,
   17.3,
   15.8,
   15.1,
   14.8,
   14.4,
   14.4,
   14.8,
   15.1,
   15.8,
   16.6,
   17.6,
   18.7,
   20.2,
   21.6,
   23.4,
   24.8,
   26.3,
   27.4,
   28.1,
   28.4,
   28.1,
   28.4,
   29.5,
   31.0,
   32.0,
   32.4,
   32.0,
   31.7,
   31.0,
   30.2,
   29.5,
   28.8,
   28.1,
   26.3,
   21.6,
   16.2,
   12.2,
   11.9,
   13.7,
   15.5,
   16.9,
   18.7,
   20.2,
   21.2,
   21.6,
   22.0,
   22.0,
   21.6,
   20.9,
   19.8,
   18.4,
   16.6,
   14.8,
   12.6,
   11.2,
   10.4,
   10.4,
   10.1,
   9.7,
   9.0,
   8.6,
   8.6,
   9.0,
   9.4,
   10.1,
   11.2,
   11.9,
   12.2,
   12.6,
   12.2,
   11.5,
   10.4,
   9.4,
   8.6,
   7.9,
   7.6,
   8.3,
   8.3,
   8.3,
   8.3,
   8.3,
   8.6,
   8.6,
   9.4,
   10.1,
   11.5,
   13.3,
   15.5,
   17.3,
   19.1,
   20.2,
   20.5,
   20.9,
   20.5,
   20.2,
   19.4,
   18.7,
   17.6,
   16.2,
   14.8,
   13.3,
   11.9],
  'temperature_2m': [8.2,
   8.2,
   7.8,
   8.1,
   8.1,
   7.9,
   7.8,
   7.9,
   7.8,
   8.5,
   9.3,
   10.5,
   11.6,
   12.1,
   12.9,
   13.6,
   13.8,
   13.1,
   12.4,
   11.5,
   11.0,
   10.9,
   10.5,
   10.1,
   9.9,
   9.9,
   10.1,
   10.1,
   9.9,
   9.4,
   8.9,
   8.9,
   8.9,
   9.1,
   10.2,
   11.1,
   12.1,
   12.6,
   12.8,
   12.9,
   12.4,
   11.8,
   11.1,
   10.4,
   9.9,
   9.7,
   9.9,
   10.0,
   10.2,
   9.8,
   9.5,
   9.8,
   9.9,
   10.1,
   10.1,
   10.1,
   9.4,
   9.8,
   10.5,
   11.0,
   11.5,
   11.7,
   11.9,
   12.0,
   11.9,
   11.7,
   11.5,
   10.9,
   10.2,
   9.5,
   9.0,
   8.5,
   8.2,
   8.2,
   8.4,
   8.6,
   8.7,
   8.8,
   8.9,
   8.9,
   9.0,
   9.2,
   9.5,
   9.9,
   10.4,
   10.8,
   11.2,
   11.5,
   11.5,
   11.5,
   11.4,
   11.4,
   11.4,
   11.4,
   11.5,
   11.6,
   11.7,
   11.9,
   12.0,
   11.6,
   10.0,
   7.9,
   6.4,
   6.2,
   6.7,
   7.2,
   7.6,
   8.1,
   8.5,
   9.1,
   9.6,
   9.9,
   10.0,
   9.8,
   9.4,
   8.9,
   8.2,
   7.5,
   7.0,
   6.5,
   6.0,
   5.7,
   5.5,
   5.2,
   4.8,
   4.3,
   4.1,
   4.2,
   4.5,
   5.1,
   6.3,
   7.9,
   9.1,
   9.8,
   10.2,
   10.4,
   10.5,
   10.5,
   10.4,
   10.2,
   9.8,
   9.5,
   9.1,
   8.6,
   8.2,
   7.6,
   6.9,
   6.2,
   5.6,
   5.3,
   5.2,
   5.7,
   6.5,
   7.6,
   8.7,
   9.7,
   10.3,
   10.7,
   10.8,
   10.9,
   10.8,
   10.7,
   10.6,
   10.5,
   10.4,
   10.1,
   9.9,
   9.7],
  'shortwave_radiation': [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   6.0,
   40.0,
   121.0,
   188.0,
   248.0,
   315.0,
   206.0,
   178.0,
   190.0,
   176.0,
   102.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   6.0,
   17.0,
   54.0,
   210.0,
   346.0,
   474.0,
   432.0,
   328.0,
   273.0,
   127.0,
   40.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   16.0,
   129.0,
   272.0,
   352.8,
   453.5,
   512.2,
   540.0,
   494.0,
   414.0,
   300.0,
   162.0,
   38.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   11.0,
   93.0,
   243.0,
   263.0,
   150.0,
   132.0,
   220.0,
   101.0,
   62.0,
   56.0,
   19.0,
   5.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   31.0,
   132.0,
   246.0,
   358.0,
   462.0,
   529.0,
   539.0,
   498.0,
   420.0,
   312.0,
   186.0,
   57.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   24.0,
   100.0,
   172.0,
   193.0,
   158.0,
   111.0,
   84.0,
   70.0,
   57.0,
   44.0,
   30.0,
   10.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   43.0,
   170.0,
   303.0,
   413.0,
   493.0,
   533.0,
   532.0,
   489.0,
   412.0,
   310.0,
   191.0,
   64.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0]}}

In [98]:
data = response['hourly']
data

{'time': ['2026-03-09T00:00',
  '2026-03-09T01:00',
  '2026-03-09T02:00',
  '2026-03-09T03:00',
  '2026-03-09T04:00',
  '2026-03-09T05:00',
  '2026-03-09T06:00',
  '2026-03-09T07:00',
  '2026-03-09T08:00',
  '2026-03-09T09:00',
  '2026-03-09T10:00',
  '2026-03-09T11:00',
  '2026-03-09T12:00',
  '2026-03-09T13:00',
  '2026-03-09T14:00',
  '2026-03-09T15:00',
  '2026-03-09T16:00',
  '2026-03-09T17:00',
  '2026-03-09T18:00',
  '2026-03-09T19:00',
  '2026-03-09T20:00',
  '2026-03-09T21:00',
  '2026-03-09T22:00',
  '2026-03-09T23:00',
  '2026-03-10T00:00',
  '2026-03-10T01:00',
  '2026-03-10T02:00',
  '2026-03-10T03:00',
  '2026-03-10T04:00',
  '2026-03-10T05:00',
  '2026-03-10T06:00',
  '2026-03-10T07:00',
  '2026-03-10T08:00',
  '2026-03-10T09:00',
  '2026-03-10T10:00',
  '2026-03-10T11:00',
  '2026-03-10T12:00',
  '2026-03-10T13:00',
  '2026-03-10T14:00',
  '2026-03-10T15:00',
  '2026-03-10T16:00',
  '2026-03-10T17:00',
  '2026-03-10T18:00',
  '2026-03-10T19:00',
  '2026-03-10T20:00',
  '2026-03-10T21:00',
  '2026-03-10T22:00',
  '2026-03-10T23:00',
  '2026-03-11T00:00',
  '2026-03-11T01:00',
  '2026-03-11T02:00',
  '2026-03-11T03:00',
  '2026-03-11T04:00',
  '2026-03-11T05:00',
  '2026-03-11T06:00',
  '2026-03-11T07:00',
  '2026-03-11T08:00',
  '2026-03-11T09:00',
  '2026-03-11T10:00',
  '2026-03-11T11:00',
  '2026-03-11T12:00',
  '2026-03-11T13:00',
  '2026-03-11T14:00',
  '2026-03-11T15:00',
  '2026-03-11T16:00',
  '2026-03-11T17:00',
  '2026-03-11T18:00',
  '2026-03-11T19:00',
  '2026-03-11T20:00',
  '2026-03-11T21:00',
  '2026-03-11T22:00',
  '2026-03-11T23:00',
  '2026-03-12T00:00',
  '2026-03-12T01:00',
  '2026-03-12T02:00',
  '2026-03-12T03:00',
  '2026-03-12T04:00',
  '2026-03-12T05:00',
  '2026-03-12T06:00',
  '2026-03-12T07:00',
  '2026-03-12T08:00',
  '2026-03-12T09:00',
  '2026-03-12T10:00',
  '2026-03-12T11:00',
  '2026-03-12T12:00',
  '2026-03-12T13:00',
  '2026-03-12T14:00',
  '2026-03-12T15:00',
  '2026-03-12T16:00',
  '2026-03-12T17:00',
  '2026-03-12T18:00',
  '2026-03-12T19:00',
  '2026-03-12T20:00',
  '2026-03-12T21:00',
  '2026-03-12T22:00',
  '2026-03-12T23:00',
  '2026-03-13T00:00',
  '2026-03-13T01:00',
  '2026-03-13T02:00',
  '2026-03-13T03:00',
  '2026-03-13T04:00',
  '2026-03-13T05:00',
  '2026-03-13T06:00',
  '2026-03-13T07:00',
  '2026-03-13T08:00',
  '2026-03-13T09:00',
  '2026-03-13T10:00',
  '2026-03-13T11:00',
  '2026-03-13T12:00',
  '2026-03-13T13:00',
  '2026-03-13T14:00',
  '2026-03-13T15:00',
  '2026-03-13T16:00',
  '2026-03-13T17:00',
  '2026-03-13T18:00',
  '2026-03-13T19:00',
  '2026-03-13T20:00',
  '2026-03-13T21:00',
  '2026-03-13T22:00',
  '2026-03-13T23:00',
  '2026-03-14T00:00',
  '2026-03-14T01:00',
  '2026-03-14T02:00',
  '2026-03-14T03:00',
  '2026-03-14T04:00',
  '2026-03-14T05:00',
  '2026-03-14T06:00',
  '2026-03-14T07:00',
  '2026-03-14T08:00',
  '2026-03-14T09:00',
  '2026-03-14T10:00',
  '2026-03-14T11:00',
  '2026-03-14T12:00',
  '2026-03-14T13:00',
  '2026-03-14T14:00',
  '2026-03-14T15:00',
  '2026-03-14T16:00',
  '2026-03-14T17:00',
  '2026-03-14T18:00',
  '2026-03-14T19:00',
  '2026-03-14T20:00',
  '2026-03-14T21:00',
  '2026-03-14T22:00',
  '2026-03-14T23:00',
  '2026-03-15T00:00',
  '2026-03-15T01:00',
  '2026-03-15T02:00',
  '2026-03-15T03:00',
  '2026-03-15T04:00',
  '2026-03-15T05:00',
  '2026-03-15T06:00',
  '2026-03-15T07:00',
  '2026-03-15T08:00',
  '2026-03-15T09:00',
  '2026-03-15T10:00',
  '2026-03-15T11:00',
  '2026-03-15T12:00',
  '2026-03-15T13:00',
  '2026-03-15T14:00',
  '2026-03-15T15:00',
  '2026-03-15T16:00',
  '2026-03-15T17:00',
  '2026-03-15T18:00',
  '2026-03-15T19:00',
  '2026-03-15T20:00',
  '2026-03-15T21:00',
  '2026-03-15T22:00',
  '2026-03-15T23:00'],
 'wind_speed_10m': [4.7,
  5.8,
  4.7,
  3.2,
  4.0,
  4.0,
  4.3,
  3.6,
  3.2,
  4.7,
  2.5,
  2.9,
  5.4,
  5.0,
  5.0,
  9.0,
  11.2,
  11.2,
  12.2,
  11.2,
  10.4,
  11.2,
  11.2,
  7.9,
  6.8,
  10.8,
  10.1,
  9.4,
  12.2,
  10.4,
  9.4,
  9.0,
  9.4,
  7.9,
  9.4,
  12.2,
  13.3,
  15.5,
  15.5,
  17.3,
  17.6,
  18.4,
  18.4,
  17.6,
  16.6,
  15.5,
  16.6,
  17.6,
  19.4,
  20.5,
  19.4,
  22.7,
  20.2,
  12.6,
  11.9,
  14.8,
  17.6,
  17.3,
  18.2,
  17.8,
  17.8,
  17.6,
  17.6,
  17.6,
  17.6,
  17.3,
  17.3,
  15.8,
  15.1,
  14.8,
  14.4,
  14.4,
  14.8,
  15.1,
  15.8,
  16.6,
  17.6,
  18.7,
  20.2,
  21.6,
  23.4,
  24.8,
  26.3,
  27.4,
  28.1,
  28.4,
  28.1,
  28.4,
  29.5,
  31.0,
  32.0,
  32.4,
  32.0,
  31.7,
  31.0,
  30.2,
  29.5,
  28.8,
  28.1,
  26.3,
  21.6,
  16.2,
  12.2,
  11.9,
  13.7,
  15.5,
  16.9,
  18.7,
  20.2,
  21.2,
  21.6,
  22.0,
  22.0,
  21.6,
  20.9,
  19.8,
  18.4,
  16.6,
  14.8,
  12.6,
  11.2,
  10.4,
  10.4,
  10.1,
  9.7,
  9.0,
  8.6,
  8.6,
  9.0,
  9.4,
  10.1,
  11.2,
  11.9,
  12.2,
  12.6,
  12.2,
  11.5,
  10.4,
  9.4,
  8.6,
  7.9,
  7.6,
  8.3,
  8.3,
  8.3,
  8.3,
  8.3,
  8.6,
  8.6,
  9.4,
  10.1,
  11.5,
  13.3,
  15.5,
  17.3,
  19.1,
  20.2,
  20.5,
  20.9,
  20.5,
  20.2,
  19.4,
  18.7,
  17.6,
  16.2,
  14.8,
  13.3,
  11.9],
 'temperature_2m': [8.2,
  8.2,
  7.8,
  8.1,
  8.1,
  7.9,
  7.8,
  7.9,
  7.8,
  8.5,
  9.3,
  10.5,
  11.6,
  12.1,
  12.9,
  13.6,
  13.8,
  13.1,
  12.4,
  11.5,
  11.0,
  10.9,
  10.5,
  10.1,
  9.9,
  9.9,
  10.1,
  10.1,
  9.9,
  9.4,
  8.9,
  8.9,
  8.9,
  9.1,
  10.2,
  11.1,
  12.1,
  12.6,
  12.8,
  12.9,
  12.4,
  11.8,
  11.1,
  10.4,
  9.9,
  9.7,
  9.9,
  10.0,
  10.2,
  9.8,
  9.5,
  9.8,
  9.9,
  10.1,
  10.1,
  10.1,
  9.4,
  9.8,
  10.5,
  11.0,
  11.5,
  11.7,
  11.9,
  12.0,
  11.9,
  11.7,
  11.5,
  10.9,
  10.2,
  9.5,
  9.0,
  8.5,
  8.2,
  8.2,
  8.4,
  8.6,
  8.7,
  8.8,
  8.9,
  8.9,
  9.0,
  9.2,
  9.5,
  9.9,
  10.4,
  10.8,
  11.2,
  11.5,
  11.5,
  11.5,
  11.4,
  11.4,
  11.4,
  11.4,
  11.5,
  11.6,
  11.7,
  11.9,
  12.0,
  11.6,
  10.0,
  7.9,
  6.4,
  6.2,
  6.7,
  7.2,
  7.6,
  8.1,
  8.5,
  9.1,
  9.6,
  9.9,
  10.0,
  9.8,
  9.4,
  8.9,
  8.2,
  7.5,
  7.0,
  6.5,
  6.0,
  5.7,
  5.5,
  5.2,
  4.8,
  4.3,
  4.1,
  4.2,
  4.5,
  5.1,
  6.3,
  7.9,
  9.1,
  9.8,
  10.2,
  10.4,
  10.5,
  10.5,
  10.4,
  10.2,
  9.8,
  9.5,
  9.1,
  8.6,
  8.2,
  7.6,
  6.9,
  6.2,
  5.6,
  5.3,
  5.2,
  5.7,
  6.5,
  7.6,
  8.7,
  9.7,
  10.3,
  10.7,
  10.8,
  10.9,
  10.8,
  10.7,
  10.6,
  10.5,
  10.4,
  10.1,
  9.9,
  9.7],
 'shortwave_radiation': [0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  6.0,
  40.0,
  121.0,
  188.0,
  248.0,
  315.0,
  206.0,
  178.0,
  190.0,
  176.0,
  102.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  6.0,
  17.0,
  54.0,
  210.0,
  346.0,
  474.0,
  432.0,
  328.0,
  273.0,
  127.0,
  40.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  16.0,
  129.0,
  272.0,
  352.8,
  453.5,
  512.2,
  540.0,
  494.0,
  414.0,
  300.0,
  162.0,
  38.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  11.0,
  93.0,
  243.0,
  263.0,
  150.0,
  132.0,
  220.0,
  101.0,
  62.0,
  56.0,
  19.0,
  5.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  31.0,
  132.0,
  246.0,
  358.0,
  462.0,
  529.0,
  539.0,
  498.0,
  420.0,
  312.0,
  186.0,
  57.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  24.0,
  100.0,
  172.0,
  193.0,
  158.0,
  111.0,
  84.0,
  70.0,
  57.0,
  44.0,
  30.0,
  10.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  43.0,
  170.0,
  303.0,
  413.0,
  493.0,
  533.0,
  532.0,
  489.0,
  412.0,
  310.0,
  191.0,
  64.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0]}

In [100]:
df = pd.DataFrame(data)
df

                 time  wind_speed_10m  temperature_2m  shortwave_radiation
0    2026-03-09T00:00             4.7             8.2                  0.0
1    2026-03-09T01:00             5.8             8.2                  0.0
2    2026-03-09T02:00             4.7             7.8                  0.0
3    2026-03-09T03:00             3.2             8.1                  0.0
4    2026-03-09T04:00             4.0             8.1                  0.0
..                ...             ...             ...                  ...
163  2026-03-15T19:00            17.6            10.5                  0.0
164  2026-03-15T20:00            16.2            10.4                  0.0
165  2026-03-15T21:00            14.8            10.1                  0.0
166  2026-03-15T22:00            13.3             9.9                  0.0
167  2026-03-15T23:00            11.9             9.7                  0.0

[168 rows x 4 columns]

# Data Preprocessing

In [103]:
df.shape

(168, 4)

In [110]:
df.isnull().sum()

time                   0
wind_speed_10m         0
temperature_2m         0
shortwave_radiation    0
dtype: int64

In [113]:
df.dtypes

time                    object
wind_speed_10m         float64
temperature_2m         float64
shortwave_radiation    float64
dtype: object